### ISSUE TITLE
Typos in seed data for guidance drop-down

### ISSUE THREAD

**Issue by jaygooby** [InnovateUKGitHub/innovation-funding-service#1]
Although these are errors in the seed data, they are appearing in the live guidance that assessors see (I'm assessing Open Round 3 and can see them).

https://github.com/InnovateUKGitHub/innovation-funding-service/blob/458178259311270dabd5a94900666264822d767f/ifs-data-layer/ifs-data-service/src/main/resources/db/setup/V86_5_3__Sector_competition_template.sql#L94

> "project . There "

should read "project. There "

https://github.com/InnovateUKGitHub/innovation-funding-service/blob/458178259311270dabd5a94900666264822d767f/ifs-data-layer/ifs-data-service/src/main/resources/db/setup/V86_5_3__Sector_competition_template.sql#L153

> "There is a T good awareness "

should read "There is a good awareness "

https://github.com/InnovateUKGitHub/innovation-funding-service/blob/458178259311270dabd5a94900666264822d767f/ifs-data-layer/ifs-data-service/src/main/resources/db/setup/V86_5_3__Sector_competition_template.sql#L112

> "fully identified . Innovation"

should read "fully identified. Innovation"

https://github.com/InnovateUKGitHub/innovation-funding-service/blob/458178259311270dabd5a94900666264822d767f/ifs-data-layer/ifs-data-service/src/main/resources/db/setup/V86_5_3__Sector_competition_template.sql#L193

> "team. . Expected regional impacts" 

should read "team. Expected regional impacts"

https://github.com/InnovateUKGitHub/innovation-funding-service/blob/458178259311270dabd5a94900666264822d767f/ifs-data-layer/ifs-data-service/src/main/resources/db/setup/V86_5_3__Sector_competition_template.sql#L174

> "increaseis identified and evidenced. . The "

should read "increase is identified and evidenced. The "

https://github.com/InnovateUKGitHub/innovation-funding-service/blob/458178259311270dabd5a94900666264822d767f/ifs-data-layer/ifs-data-service/src/main/resources/db/setup/V86_5_3__Sector_competition_template.sql#L274

> "(including doing nothing)..  T"

should read "(including doing nothing).  T"

**Comment by rderegt** [comment]
Thank you for reporting this. We will review and apply the changes.

**Comment by rderegt** [comment]
This has been resolved.
