### ISSUE TITLE
Open Round 3 - Risks question 8, score input is below the feedback box

### ISSUE THREAD

**Issue by jaygooby** [InnovateUKGitHub/innovation-funding-service#2]
On all the other questions, the score box appears above the feedback box, e.g. Questions 1-7, 9 & 10:

![screen shot 2017-10-01 at 16 52 37](https://user-images.githubusercontent.com/64270/31056417-2e5101b2-a6c9-11e7-93ef-a310e201ea1b.png)

Question 8:

![screen shot 2017-10-01 at 16 52 22](https://user-images.githubusercontent.com/64270/31056413-1d1ee1d4-a6c9-11e7-8540-7fd661d2de85.png)

**Comment by rderegt** [comment]
@jaygooby this looks indeed inconsistent. We will get it sorted and report back here as soon as we have resolved it. Thank you for your feedback, helping out improving the service. It's much appreciated.

**Comment by rderegt** [comment]
Thanks @jaygooby we have resolved it under ticket IFS-1957 and is already released. Many thanks for your help!
