### ISSUE TITLE
Project Summary and Public Description screens are showing raw markdown

### ISSUE THREAD

**Issue by jaygooby** [InnovateUKGitHub/innovation-funding-service#3]
When viewing an application as an assessor, The Project summary and Public description screens are showing raw markdown for the responses and not formatted html.

I've redacted almost all of the text in these screenshots, but you can see some of the markdown asterisks.

![screen shot 2018-01-01 at 14 14 48](https://user-images.githubusercontent.com/64270/34468372-5dfefe72-eeff-11e7-9524-e080be00dea0.png)

![screen shot 2018-01-01 at 14 19 19](https://user-images.githubusercontent.com/64270/34468378-8604d9b4-eeff-11e7-8e5f-d2522041f511.png)

(these are from two different applications, just to be sure it wasn't just an issue with a particular applicant)

**Comment by bdekok** [comment]
Hello everyone, 

I'm not on the project anymore, but I know what caused this. The conversion of markdown to html is done on the client, however for this to be applied there needs to be a `data-md-to-html` attribute on the output div of any editor enabled textarea. 

This works only if javascript is enabled though, as javascript converts the markdown to html. A better approach would be to have some kind of back-end markdown to html conversion, however that's quite a lot more work to do so. 

With regards,
Brent

**Comment by rderegt** [comment]
Hello,

Thanks, @jaygooby and @bdekok for your input, we have looked into it and resolved it under ticket IFS-2531. This issue is resolved in the next release.

Kind regards,

Rogier
