### ISSUE TITLE
unknown property 'openshiftEnv'

### ISSUE THREAD

**Issue by HelainSchoonjans** [InnovateUKGitHub/innovation-funding-service#5]
Dear InnovateUK,

Having downloaded the repository and imported it in Intellij Idea as a Gradle project, the build task always fail with the following message:

`Could not get unknown property 'openshiftEnv' for root project 'innovation-funding-service' of type org.gradle.api.Project.`

Would it be possible to document how to configure the project for local development? I assume I am missing some environment variable or task argument.

Thanks

**Comment by rderegt** [comment]
Please find the documentation attached to the project as readme.
